# Generated by Django 3.0.4 on 2020-03-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_user_accesspin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accesspin',
            field=models.IntegerField(default=-999),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=130),
        ),
    ]
